"""empty message

Revision ID: afb09add9464
Revises: b1fb8ce6c4ee
Create Date: 2024-06-03 20:55:19.729838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb09add9464'
down_revision = 'b1fb8ce6c4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_category_id', sa.BigInteger(), nullable=True, comment='专题分类id'),
    sa.Column('title', sa.String(length=244), nullable=True, comment='专题标题'),
    sa.Column('pic', sa.String(length=500), nullable=True, comment='专题主图'),
    sa.Column('product_count', sa.Integer(), nullable=True, comment='关联产品数量'),
    sa.Column('recommend_status', sa.Integer(), nullable=True, comment='推荐状态'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('change_person', sa.String(length=64), nullable=False, comment='更新人的名称'),
    sa.Column('create_person', sa.String(length=64), nullable=False, comment='创建人的名称'),
    sa.Column('enable', sa.SmallInteger(), nullable=False, comment='逻辑删除0-未删除，1-已删除'),
    sa.Column('merchant', sa.Integer(), nullable=True, comment='商户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_project')
    # ### end Alembic commands ###
