"""empty message

Revision ID: b1fb8ce6c4ee
Revises: 695dcfdc922b
Create Date: 2024-06-03 20:15:58.518854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fb8ce6c4ee'
down_revision = '695dcfdc922b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_recommend_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='商品id'),
    sa.Column('product_name', sa.String(length=255), nullable=True, comment='商品名称'),
    sa.Column('recommend_status', sa.Integer(), nullable=True, comment='推荐状态，0表示未推荐，1表示已推荐'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('change_person', sa.String(length=64), nullable=False, comment='更新人的名称'),
    sa.Column('create_person', sa.String(length=64), nullable=False, comment='创建人的名称'),
    sa.Column('enable', sa.SmallInteger(), nullable=False, comment='逻辑删除0-未删除，1-已删除'),
    sa.Column('merchant', sa.Integer(), nullable=True, comment='商户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_recommend_product')
    # ### end Alembic commands ###
