"""empty message

Revision ID: d26e1508671d
Revises: afb09add9464
Create Date: 2024-06-03 21:08:48.052737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26e1508671d'
down_revision = 'afb09add9464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_project', sa.Column('show_status', sa.Integer(), nullable=True, comment='显示状态，0不显示，1显示'))
    op.add_column('t_project', sa.Column('forward_count', sa.Integer(), nullable=True, comment='转发数'))
    op.add_column('t_project', sa.Column('hot_words', sa.String(length=500), nullable=True, comment='专题热词'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_project', 'hot_words')
    op.drop_column('t_project', 'forward_count')
    op.drop_column('t_project', 'show_status')
    # ### end Alembic commands ###
